### ISSUE TITLE
Doesn't work on Solus

### ISSUE THREAD

**Issue by Vistaus** [ghisvail/gnome-backgrounds-bitday#1]
I just installed gnome-backgrounds-bitday and after selecting the timed background file thingy in Settings --> Background, it just shows a plain blue wallpaper. I've also logged out and back in to no avail.

I hope you can either fix this or assist me to fix it/help you fix it :)

**Comment by ghisvail** [comment]
Since you are on Solus, I am assuming you are using the [Budgie](https://solus-project.com/budgie/) desktop. I have no idea whether `Budgie` supports dynamic wallpapers made for `GNOME`.

You would have to ask them directly via any of the support channels they provide. If the amount of modification required to provide support for `Budgie` stays reasonably limited, then I'd be happy to implement it. Otherwise, it might be worth to kick-start a different project for it.

Keep me posted.

**Comment by Vistaus** [comment]
Yes, I'm on Budgie. Forgot to mention that, sorry. But Budgie supports dynamic wallpapers made for GNOME. The Adwaita set works fine for me. budgie-wm is based on Mutter.

**Comment by ghisvail** [comment]
Did you get confirmation upstream that `Budgie` supports third-party dynamic wallpapers? This [bug](https://github.com/budgie-desktop/budgie-desktop/issues/261) (the first bullet point in particular) makes me doubt that this is actually the case.

**Comment by ghisvail** [comment]
I am also worried that, with the [planned](https://budgie-desktop.org/2017/01/25/kicking-off-budgie-11/) move to `Qt` for Budgie 11, support for GNOME related stuff will be scrapped anyway.

**Comment by Vistaus** [comment]
But in the same bug report, Ikey Doherty also says that non-working rotating wallpapers is an Arch issue rather than a Budgie issue, meaning it's supposed to work on Budgie. And in my case that's true as well, as I'm:

1 Not using Arch, I'm using Solus
2 The Adwaita rotating set works fine (which is also using an .xml file)

That's why I reported it directly to you.

It's true that Budgie is planning to move to Qt but that's planned for Q2 so right now I do want this .xml file to work. There's no other way of using those bitday wallpapers on Solus but an .xml file, so...

**Comment by ghisvail** [comment]
Assuming you followed the instructions in the README, after installation you should have the wallpaper files + xml file with the timings under `/usr/share/backgrounds/bitday` and a file `/usr/share/gnome-background-properties/bitday.xml`. Please confirm whether this is the case. If not, please run the installation again following these instructions.

In case the files and paths above are correct, please contact the Budgie desktop maintainers and ask them why Budgie fails to register the dynamic wallpaper properly, like it does for Adwaita. Assuming they provide you with a fix and you are able to validate it against your setup, then I would be happy to merge it.

**Comment by Vistaus** [comment]
I can confirm that everything's in place:

```
[13:26:00] vistaus@vistaus-solus /home/vistaus/Downloads (0) 
> cd /usr/share/backgrounds/bitday/
[13:26:08] vistaus@vistaus-solus /usr/share/backgrounds/bitday (0) 
> ls
01-Early-Morning.png  03-Late-Morning.png     05-Mid-Afternoon.png   07-Early-Evening.png  09-Late-Evening.png  11-Mid-Night.png   bitday-timed.xml
02-Mid-Morning.png    04-Early-Afternoon.png  06-Late-Afternoon.png  08-Mid-Evening.png    10-Early-Night.png   12-Late-Night.png
[13:26:09] vistaus@vistaus-solus /usr/share/backgrounds/bitday (0) 
> cd ../..
[13:26:17] vistaus@vistaus-solus /usr/share (0) 
> cd gnome-background-properties/
[13:26:26] vistaus@vistaus-solus /usr/share/gnome-background-properties (0) 
> ls
bitday.xml  gnome-default.xml  solus-wallpapers.xml
[13:26:26] vistaus@vistaus-solus /usr/share/gnome-background-properties (0) 
> 
```

I'll ask the Budgie desktop maintainers ASAP. Thanks so far! :-)

**Comment by ghisvail** [comment]
Closing the issue due to lack of activity. Pleas re-open with new information if the issue is still present.
