### ISSUE TITLE
Incorrect tag used in XML

### ISSUE THREAD

**Issue by hadess** [ghisvail/gnome-backgrounds-bitday#2]
When launching gnome-control-center you'd get:
```
(gnome-control-center:22983): background-cc-panel-WARNING **: Unknown Tag: _name
```

`<_name>` should be `<name>` as you're not translating the XML file.

**Comment by ghisvail** [comment]
Indeed. Do you want to submit a PR for it?

**Comment by hadess** [comment]
It's a one-liner, easier if you do it.

**Comment by hadess** [comment]
Thanks (and thanks for the repo as well :)
