### ISSUE TITLE
Not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by alejo9719** [ghisvail/gnome-backgrounds-bitday#7]
Hi,

I tried to install it on Ubuntu 20.04 using the files provided but the background stays the same.

Here's the output from the console:

ninja: Entering directory `builddir'
[0/1] Installing files.
Installing /home/javz/Descargas/gnome-backgrounds-bitday-master/builddir/backgrounds/bitday-timed.xml to /usr/share/backgrounds/bitday
Installing /home/javz/Descargas/gnome-backgrounds-bitday-master/backgrounds/01-Early-Morning.png to /usr/share/backgrounds/bitday
Installing /home/javz/Descargas/gnome-backgrounds-bitday-master/backgrounds/02-Mid-Morning.png to /usr/share/backgrounds/bitday
Installing /home/javz/Descargas/gnome-backgrounds-bitday-master/backgrounds/03-Late-Morning.png to /usr/share/backgrounds/bitday
Installing /home/javz/Descargas/gnome-backgrounds-bitday-master/backgrounds/04-Early-Afternoon.png to /usr/share/backgrounds/bitday
Installing /home/javz/Descargas/gnome-backgrounds-bitday-master/backgrounds/05-Mid-Afternoon.png to /usr/share/backgrounds/bitday
Installing /home/javz/Descargas/gnome-backgrounds-bitday-master/backgrounds/06-Late-Afternoon.png to /usr/share/backgrounds/bitday
Installing /home/javz/Descargas/gnome-backgrounds-bitday-master/backgrounds/07-Early-Evening.png to /usr/share/backgrounds/bitday
Installing /home/javz/Descargas/gnome-backgrounds-bitday-master/backgrounds/08-Mid-Evening.png to /usr/share/backgrounds/bitday
Installing /home/javz/Descargas/gnome-backgrounds-bitday-master/backgrounds/09-Late-Evening.png to /usr/share/backgrounds/bitday
Installing /home/javz/Descargas/gnome-backgrounds-bitday-master/backgrounds/10-Early-Night.png to /usr/share/backgrounds/bitday
Installing /home/javz/Descargas/gnome-backgrounds-bitday-master/backgrounds/11-Mid-Night.png to /usr/share/backgrounds/bitday
Installing /home/javz/Descargas/gnome-backgrounds-bitday-master/backgrounds/12-Late-Night.png to /usr/share/backgrounds/bitday
Installing /home/javz/Descargas/gnome-backgrounds-bitday-master/builddir/backgrounds/bitday.xml to /usr/share/gnome-background-properties

**Comment by ghisvail** [comment]
Can you show a screenshot of your background setup in GNOME Settings?

**Comment by alejo9719** [comment]
![imagen](https://user-images.githubusercontent.com/2808960/109667707-69506f80-7b3e-11eb-9d33-8c6326b20c9d.png)

**Comment by ghisvail** [comment]
And a screenshot of your current background

**Comment by alejo9719** [comment]
I think it was a conflict with another dynamic wallpaper I had installed using a bash script, which executed code everytime I logged into Ubuntu. I deleted the files associated with such wallpaper and BitDay started working.

Thanks!
