### ISSUE TITLE
Add support for dark/light backgrounds for GNOME 42+

### ISSUE THREAD

**Issue by saltedcoffii** [ghisvail/gnome-backgrounds-bitday#8]
This is a pretty simple addition that requires the installation of an XML file into `/usr/share/gnome-background-properties` or `~/.local/share/gnome-background-properties`.
See an example [here](https://gitlab.gnome.org/GNOME/gnome-backgrounds/-/blob/main/backgrounds/truchet.xml.in)

**Comment by ghisvail** [comment]
I share your excitement towards the new GNOME dark / light wallpapers, but I am not sure how it could be applied here. In particular, I wonder which wallpapers should be picked for the dark and light variants.

Feel free to submit a pull request with a combination you are happy with.

**Comment by saltedcoffii** [comment]
Oh yeah I don't know which ones :/

**Comment by ghisvail** [comment]
@saltedcoffii could you try #9 and report whether it works for you?

**Comment by ghisvail** [comment]
I tested it on a fresh install of Fedora 36, and get the regular timed wallpapers and 3 additional dark / light variants.

Feel free to let me know whether they fulfil your expectations.

**Comment by saltedcoffii** [comment]
I love them!! thank you so much <3
